#!/bin/bash

mybin=$1 ;   SRPL=$2

FtolRL=$3 ;  KPRL=$4
FtolRM=$5 ;  KPRM=$6
FtolRH=$7 ;  KPRH=$8 ;  nstep=$9


echo -e "which -a $mybin :\n" `which -a $mybin` "\n"
echo -e "SRPL:" $SRPL "\n"
echo -e "Low:"  $FtolRL $KPRL "\n"
echo -e "Med:"  $FtolRM $KPRM "\n"
echo -e "High:" $FtolRH $KPRH  $nstep "\n"




#==============================
date 
SECONDS=0
yin_slurm_vasp_job_pre


#==============================
if   [ "$SRPL" = "L" ] ; then
  flagL=1  ; flagM=1;

elif [ "$SRPL" = "M" ] ; then
  flagL=0  ; flagM=1;

elif [ "$SRPL" = "H" ] ; then
  flagL=0  ; flagM=0;
fi


#==============================
if [ "$flagL" = "1" ] ; then
    yin_vasp_univ_find_and_change  -lreal    A  
    yin_vasp_univ_find_and_change  -ediffg   $FtolRL 
    yin_vasp_univ_find_and_change  -kp       $KPRL
    
    yin_slurm_vasp_job_relax_while  $mybin  "Low"  "y_RL_notes" 

    yin_vasp_univ_find_and_change  -lreal    A  
    yin_vasp_univ_find_and_change  -ediffg   $FtolRM
    yin_vasp_univ_find_and_change  -kp       $KPRM
fi


#==============================
if [ "$flagM" = "1" ] ; then
    yin_slurm_vasp_job_relax_while  $mybin  "Med"  "y_RM_notes" 

    yin_vasp_univ_find_and_change  -lreal    F 
    yin_vasp_univ_find_and_change  -ediffg   $FtolRH
    yin_vasp_univ_find_and_change  -kp       $KPRH
fi


#==============================
yin_slurm_vasp_relax_for  $mybin  $nstep  


#==============================
date
yin_slurm_vasp_job_echo_time $SECONDS



