#!/bin/bash


echo -e "\nSLURM_JOBID        =" $SLURM_JOBID
echo -e   "SLURM_JOB_NODELIST =" $SLURM_JOB_NODELIST
echo -e   "SLURM_NNODES       =" $SLURM_NNODES
echo -e   "SLURM_SUBMIT_DIR   =" $SLURM_SUBMIT_DIR "\n"

echo -e "pwd :\n" `pwd` "\n"
echo -e "bash --version :\n" `bash --version` "\n"
echo -e "uname -a :\n" `uname -a` "\n"
echo -e "cat /etc/system-release :\n" `cat /etc/system-release` "\n"



#==============================

echo -e "\n"`date`"\n" >  y_oszicar
echo -e "\n"`date`"\n" >  y_outcar
echo -e "\n"`date`"\n" >> y_poscar

echo -e "\n"`date`"\n initial POSCAR: \n" >> y_poscar
cat POSCAR >> y_poscar


