#!/bin/bash
# B. Yin, 2017-06-12




echo "Type the fisrt JobID, [ENTER]:"
read ids


echo "Type the last JobID, [ENTER]:"
read ide


echo "canceling jobs from" $ids "to" $ide



for ((i=$ids; i<=$ide; i=i+1))  
do

echo $i
scancel $i

done



